### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by likelet** [likelet/LncPipe#5]
- [x] provide input format for [IDEA](https://github.com/likelet/IDEA)
- [ ] Add lncRNA identification method by LGC(http://bigd.big.ac.cn/biocode/tools/BT000004)
- [ ] integrate report by MultiQC(http://multiqc.info/)
- [ ] Functional classification by [SEEKR](https://www.nature.com/articles/s41588-018-0207-8)
- [ ] Add protein-coding ability predicting by CPC2
- [ ] Update fastp call method by STDOUT (not implemented )
- [ ] Add section for predicting lncRNA target based on nucleic and thermodynamics, may be lncRNATargets?
- [ ] Add lncRNA filtering step by using Pfam, RNAFold, Infernal/cmscan
- [x] Remove the functions that can automatically build the index for alignment.
- [x] '-resume' not working for the alignment step. 
- [x] Add support for  skipping QC analysis steps

**Comment by sateeshperi** [comment]
Can i suggest an enhancement via incorporation of MultiQC tool (http://multiqc.info/) to summarize QC results from many samples into one file for easy viewing.

**Comment by likelet** [comment]
I have been following MultiQC for a long time ( start before it was published on Bioinformatics). ewels did a good job on visualizing and summarizing reports by multiple samples. It also provided framework allowing people add modules in his software, which draw great attention from developers. One of the best tools I had seen in GitHub.  

I was thinking to try using multiQC in this project at the very start . But for that time, its not mature enough to do so  as multiQC was designed as a general tool incorporation with many software output, which means its may not be easily modified for my own output structure(a possible reason that  I am not familiar with python programing as well as solving configuration of dependencies).  

But recently, I found multiQC can deal with output from plenty of tools and there also have a community to solve questions. So I am about to rethink that improving our reporting system  by introducing MultiQC. 

So would you like to do so? Since I am not a pythoner but a java programer and do not have enough energy to do the multiQC project. Not just LncPipe, we have many other similar projects under development  that  also require such feature.

**Comment by sateeshperi** [comment]
I recently started Python programming and have no JAVA background, so it would be a time-consuming task for me too. But, If you like, I can ask around to see if any of my Python friends would be willing to pitch in and incorporate it into the pipeline.

**Comment by likelet** [comment]
It's just a python issue, JAVA programming is not necessary for report organization. I prefer your involvement rather than anyone else as they do not know LncPipe as much as you do :)
